project_id = "klhebfqxfgepacruplxy"

[functions.validate-license]
verify_jwt = false

[functions.activate-license]
verify_jwt = true

[functions.notify-account-lock]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.check-deadlines]
verify_jwt = false

[functions.check-api-key-status]
verify_jwt = true
